# Generated by Django 4.0.6 on 2022-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20)),
                ('size', models.SmallIntegerField()),
                ('material', models.CharField(max_length=25)),
                ('price', models.IntegerField(blank=True)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('quantity', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
