# Generated by Django 4.0.6 on 2022-08-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.IntegerField(primary_key=3, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('Id', models.IntegerField(primary_key=4, serialize=False)),
                ('quantity', models.BigIntegerField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('Id', models.IntegerField(primary_key=1, serialize=False)),
                ('clothing_name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(max_length=20, null=True)),
                ('size', models.SmallIntegerField()),
                ('material', models.CharField(max_length=25, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('brand', models.CharField(max_length=20)),
                ('clothing_image', models.ImageField(blank=True, upload_to='')),
                ('quantity', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('Id', models.IntegerField(primary_key=2, serialize=False)),
                ('cosmetics_name', models.CharField(blank=True, max_length=20)),
                ('cosmetics_image', models.ImageField(blank=True, upload_to='')),
                ('color', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='clothing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clothing'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cosmetics_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cosmetics'),
        ),
    ]
