# Generated by Django 4.0.6 on 2022-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart_cartitem_clothing_cosmetics_delete_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
