# Generated by Django 4.0.6 on 2022-08-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_Id', models.IntegerField(primary_key=2, serialize=False)),
                ('quantity', models.BigIntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_Id', models.IntegerField(primary_key=1, serialize=False)),
                ('size', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('quantity_in_stock', models.BigIntegerField(blank=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField(default=1)),
                ('category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Id',
            new_name='cart_Id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='Id',
            new_name='cartItem_Id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_Id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='clothing_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cosmetics_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='number_of_products',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Cosmetics',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
