# Generated by Django 4.0.6 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categories_product_rename_id_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_Id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Id',
            field=models.IntegerField(primary_key=2, serialize=False),
        ),
    ]
