# Generated by Django 4.0.6 on 2022-08-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_categories_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_id',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
